media:
 input: src/content/media
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    filename: '{primary}.mdx'
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: string
      - name: pubDate
        label: Publication Date
        type: date
        format: yyyy-MM-dd
        required: true
      - name: status
        label: Status
        type: select
        options:
            values: [ draft, published ]
        required: true
      - name: author
        label: Author
        type: string
      - name: tags
        label: Tags
        type: string
        list: true
      - name: body
        label: Body
        type: rich-text
        required: true
      - name: cover
        label: Cover
        type: object
        fields: 
          - name: src
            label: Cover image
            type: image
          - name: title
            label: Title
            type: string
          - name: alt
            label: ALT
            type: string
  

      
  - name: CONFIG
    label: "Blog Config"
    type: file
    path: blog-config.yaml
    fields: 
      - name: TITLE
        label: Blog title
        type: string
      - name: URL
        label: Blog url
        type: string
      - name: DESCRIPTION
        label: Blog description
        type: string
      - name: LANG
        label: Blog language
        type: string
        default: EN
      - name: AUTHOR
        label: Author name
        type: string
      - name: CONTACT
        label: Display contact email
        type: boolean
      - name: EMAIL
        label: Contact email
        type: string
      - name: POST_COVER
        label: Display post cover
        type: boolean
        default: true
      - name: POST_THUMBNAILS
        label: Display post thumbnails
        type: boolean
        default: true
      - name: POST_SUGGESTIONS
        label: Display post suggestions
        type: boolean
        default: true
      - name: HOME_NB_POSTS
        label: Number posts on homepage
        type: number
        default: 6
      - name: MENU
        label: Navigation menu
        type: object
        list: true
        fields:
          - name: label
            label: Label
            type: string
          - name: url
            label: URL
            type: string
